import { SecondaryNavItemType } from '@/features/layout/'

export const secondaryNavItems: SecondaryNavItemType[] = [
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '/assets/secondNav/Rectangle29.webp',
	},
]
