import { SecondaryHeaderItemsType } from '@/features/layout/'

export const secondaryHeaderItems: SecondaryHeaderItemsType[] = [
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
	{
		title: 'Menu Item',
		url: '#',
		items: [
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
			{
				title: 'Header',
				url: '#',
				items: [
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
					{ title: 'Subheader', url: '#' },
				],
			},
		],
		menuImage: '#',
	},
]
